services:
  - type: web
    name: beautydesk-public-booking-web
    runtime: static
    buildCommand: ""
    staticPublishPath: .
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
